s = set()
n = int(input("Enter the number :"))
s.add(n)
n = int(input("Enter the number :"))
s.add(n)
n = int(input("Enter the number :"))
s.add(n)
n = int(input("Enter the number :"))
s.add(n)
n = int(input("Enter the number :"))
s.add(n)
n = int(input("Enter the number :"))
s.add(n)
n = int(input("Enter the number :"))
s.add(n)
n = int(input("Enter the number :"))
s.add(n)

print(s)